
library(shiny)
library(DT)




shinyUI(
  navbarPage(title = "MiniCEx Analyses",
             id = "navbar",
             theme = shinythemes::shinytheme("yeti"),
             
             tabPanel(title = "How to use this app",
                      sidebarPanel(fileInput(inputId = "minicex_file",
                                             label = "Upload your MiniCEx.xlsx file here"),
                                   fileInput(inputId = "edits",
                                             label = "Upload your MiniCEx Rows_To_Edit.xlsx file here")),
                      mainPanel(fluidPage(imageOutput("logo", inline = TRUE),
                                          tags$h1("Welcome to the R(D)SVS MiniCEx App"),
                                          tags$p("This app is intended to process and report on the MiniCEx data
                                           generated by final year students. It was designed by Jill MacKay and the source code
                                           can be found", tags$a(href = "https://github.com/jillymackay/MiniCEx",  "on github here."), 
                                           "The intention is that the Final Year team can use this dashboard to process the MiniCEx data
                                           at will. If there are any issues with the app, please contact Jill with as full a description of
                                           the issue as possible.", tags$em("The most likely issue is that the edit file is no longer compatible"), 
                                           "and this may be fixed by reverting the last changes if possible." ),
                                          tags$p("At present, the app requires you to upload two files:"),
                                          tags$ol(tags$li("A MiniCEx file",
                                                          tags$ul("This should be the MiniCEx file as you download it from the FY Teams page.
                                                                  Do not make any edits to this file.")),
                                                  tags$li("A MiniCEx edit file",
                                                          tags$ul("This file should look like the MiniCEx file but have only the rows you want to 
                                                                  edit and have the timetable in a second sheet, ie see Fieldsec/BVMS Years/
                                                                  Final Year/MiniCEx Analyses/AY 2023-2024/App Data - Save Your MiniCEx Spreadsheet Here
                                                                  /FY MiniCE 2023_2024_RowsToEdit.xlsx")))
                                          ),
                                fluidRow(tags$h2("MiniCEx Snapshot"),
                                         tags$p("Once your MiniCEx data is uploaded it will appear here. It shoud look like your excel file, but with some extra columns at the end.
                                                If this doesn't look right at this stage, double check that your file hasn't been changed from the version downloaded
                                                from Sharepoint."),
                                         tags$p("You can search and browse through the MiniCEx data here, e.g. search for student matric `s1234567` or assessor `Alex Corbishley`."),
                                         DTOutput("raw_data")),
                                fluidRow(tags$h2("Yearlist Snapshot"),
                                         DTOutput("raw_yl"))
                                )
                      ),
             
             
             tabPanel(title = "MiniCEx Report",
                      fluidPage(fluidRow(column(width = 12,
                                                tags$h1("About this report"),
                                                tags$p("This is an in-development version of an app to analyse MiniCEx data. The intention is that the FY team at R(D)SVS will be able to use this app to process and analyse MiniCEx data as needed."),
                                                tags$h4("Version 1"),
                                                tags$h2("Notes"),
                                                tags$h3("Date of data:"),
                                                tags$p("The last entry in this MiniCEx file is from date:", textOutput("s_dateofdata")),
                                                tags$h2("MiniCEx Submissions to Check"),
                                                tags$p("These data have an issue where the matriculation number does not match with data collected by MS Forms. 
                                                       These are likely typos in the matriculation but should be reviewed by a human eye and the matriculation number #
                                                       potentially changed in the background spreadsheet. Note, these entries will be creating some errors in the data,
                                                       e.g. potentially showing a student has fewer than required number of MiniCExs until they are fixed."),
                                                tableOutput(outputId = "t_matsmatch"),
                                                tags$h2("Students who have not yet contributed a MiniCEx"),
                                                tags$p("Note: this table requires a valid timetable to be uploaded"),
                                                DTOutput(outputId = "t_nocontrib"),
                                                tags$h2("Students who have completed fewer than the required number of tasks"),
                                                tableOutput(outputId = "t_net")
                      )),
                      fluidRow(column(width = 12,
                                      tags$h2("Distribution of task type by date"),
                                      plotOutput(outputId = "p_datetasks"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Species used for MiniCEx per student"),
                                      plotOutput(outputId = "p_sppxmat"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Species logged per week"),
                                      plotOutput(outputId = "p_sppxweek"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Overall performance marks by date"),
                                      plotOutput(outputId = "p_fbackxweek", hover = hoverOpts(id = "ph_fbackxweek", delay = 50)),
                                      uiOutput("my_tooltip"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Overall performance by species and date"),
                                      plotOutput(outputId = "p_fbackxweekfspp"),
                                      plotOutput(outputId = "p_fbackxspp"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Students performing below expected level"),
                                      tags$p("Students who performed below expected level, task and assessor shown. New students shown at bottom of table"),
                                      tableOutput(outputId = "t_below"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Entrustability scores by student"),
                                      plotOutput(outputId = "p_entrustxmatric"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Entrustability by Task"),
                                      plotOutput(outputId = "p_entrustxtask"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Overall feedback by Task"),
                                      plotOutput(outputId = "p_fbackxtask"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Students with no surgery task"),
                                      tableOutput(outputId = "t_nosurg"))),
                      fluidRow(column(width = 12,
                                      tags$h2("Rotations"),
                                      tableOutput(outputId = "t_rotations")))
                      )),
             
             
             
             # -------------- Output -----------------------         
             
             
             
             
             # -------------- Inglis Report ----------------
             
             tabPanel(title = "Inglis Check",
                      fluidPage(tags$h2("About this page"),
                                tags$p("This report aims to highlight students at Inglis", 
                                       tags$em(" this week "), 
                                       "who have not yet completed two MiniCExs. It is recommended you run this report mid-week."),
                                tags$em("Note, you will need a timetable file and MiniCEx file uploaded in the 'Upload' tab to run this report."),
                                tags$h3("These students are thought to be at Inglis this week"),
                                DTOutput("inglisthisweek"),
                                tags$h3("Students believed to be at Inglis this week with NO MiniCExs recorded"),
                                DTOutput("inglisthisweek_none"),
                                tags$h3("Students believed to be at Inglis this week with recorded tasks"),
                                DTOutput("inglis_tasks"),
                                tags$h3("Students believed to be at Inglis this week with fewer than 2 tasks recorded"),
                                DTOutput("inglis_tasks_less2"),
                                tags$h3("Tasks at Inglis This Week"),
                                DTOutput("inglis_fulltasks")
                      ))
             
             
             
             
             
             
             # ------------- app close brackets---------------
             
))